#mp相关的设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: czh66221183
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
# 配置建的策略,防止用mabtis 的策略会乱码
      id-type: auto
# 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

