#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: czh66221183
#    type: com.alibaba.druid.pool.DruidDataSource
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: mysql://localhost:3306/ssm?serverTimezone=UTC
      username: root
      password: czh66221183