spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ssm?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: czh66221183

#mp相关的设置